name: vitest
on: [push, pull_request]

jobs:
  vitest:
    name: vitest
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests Check
        run: pnpm test:coverage

      - name: Report Coverage
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2